config/routes.rb
SteppedCareReboot::Application.routes.draw do
  devise_for :participants
  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  scope constraints: { format: 'html' } do
    get 'navigator/next_content', to: 'navigator#show_next_content', as: 'navigator_next_content'
    get 'navigator/contexts/:context_name', to: 'navigator#show_context', as: 'navigator_context'
    get 'navigator/modules/:module_id(/providers/:provider_id/:content_position)', to: 'navigator#show_location', as: 'navigator_location'
    resource :participant_data, only: [:create, :update]
    resource :flow, only: :show
  end

  resources :slideshows do
    resources :slides do
      collection { post :sort }
    end
  end

  namespace :manage do
    get 'groups/:id/edit_slideshows', to: 'groups#edit_slideshows', as: 'slideshows_group'
    get 'groups/:id/edit_tasks', to: 'groups#edit_tasks', as: 'tasks_group'
    resources :groups, only: [:index]
    resources :tasks, only: [:create, :update, :destroy]
  end

  namespace :coach do
    resources :messages, only: [:index, :new, :create]
    resources :received_messages, only: [:index, :show]
    resources :sent_messages, only: :show
  end

  namespace :participants do
    resources :phq_assessments, only: [:new, :create]
    resources :received_messages, only: :index
    resources :task_status, only: [:update]
  end

  root to: 'navigator#show_context'

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end
end

app/models/emotion.rb
# Participants rate their emotions with valence and intensity
class Emotion < ActiveRecord::Base
  belongs_to :participant
  validates :participant, presence: true
  validates :valence, presence: true, inclusion: { in: -1..1 }
  validates :rating, presence: true, inclusion: { in: 0..10 }

  def intensity_value
    Values::Emotion.from_intensity(intensity).to_s
  end

  def rating_value
    Values::Emotion.from_rating(rating).to_s
  end
end

app/models/values/emotion.rb
module Values
  # Participants rate their emotion with a valence and intensity
  class Emotion
    def self.from_intensity(intensity)
      return "Not answered" if intensity.nil?
      if intensity < 5
        new("Low")
      elsif intensity == 5
        new("Average")
      else
        new("High")
      end
    end

    def self.from_rating(rating)
      return "Not answered" if rating.nil?
      if rating < 5
        new("Bad")
      elsif rating == 5
        new("Neither")
      else
        new("Good")
      end
    end

    def initialize(label)
      @label = label
    end

    def to_s
      @label.to_s
    end
  end
end

app/helpers/emotions_helper.rb
# Used to change color of table row based on emotion
module EmotionsHelper
  def emotion_class(emotion)
    case emotion.rating
    when 0..4
      "danger"
    when 6..10
      "success"
    else
      ""
    end
  end
end

app/views/emotions/_emotion.html.erb
<tr class="<%= emotion_class(emotion) %>">
  <td><%= emotion.name %></td>
  <td><%= time_ago_in_words(emotion.created_at) %> ago</td>
  <td><%= emotion.rating %></td>
</tr>

app/views/emotions/energy_intensity.html.erb
<h3>Emotion Details</h3>
<%= form_for emotion, url: update_path, method: "post", html: { role: "form" } do |f| %>
  <%= f.hidden_field :rating, value: emotion.rating %>

  <%= f.label :activation_level, "Select the word that best describes the emotion" %>
  <%= f.select(:activation_level, options_for_select(emotion_types)) %>

  <br>
  <%= f.label :intensity %>
  <div class="range row">
    <div class="col-sm-6 left">1<br>Low</div>
    <div class="col-sm-6 right">10<br>High</div>
  </div>
  <%= f.range_field :intensity, in: 0..10, step: 1 %>

  <%= f.submit "Continue", class: "btn btn-primary" %>
<% end %>

app/views/emotions/index.html.erb
<h3>Your Recent Emotions</h3>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Recorded</th>
      <th>Rating</th>
    </tr>
  </thead>
  <tbody>
    <%= render emotions %>
  </tbody>
</table>

app/views/emotions/new.html.erb
<h3>Over the past 24 hours, what emotions did you experience?</h3>
<%= form_for emotion, url: create_path, method: "post", html: { role: "form" } do |f| %>

  <%= f.label :activation_level, "How energetic were you yesterday?" %>
  <div class="range row">
    <div class="col-sm-4 left">-5<br>Passive</div>
    <div class="col-sm-4 text-center">0<br>Average</div>
    <div class="col-sm-4 right">5<br>Active</div>
  </div>
  <%= f.range_field :activation_level, in: -5..5, step: 1, value: 0 %>

  <%= f.label :rating, "Did you feel bad, good, or neither yesterday?" %>
  <div class="range row">
    <div class="col-sm-4 left">-5<br>Bad</div>
    <div class="col-sm-4 text-center">0<br>Neither</div>
    <div class="col-sm-4 right">5<br>Good</div>
  </div>
  <%= f.range_field :rating, in: -5..5, step: 1, value: 0 %>

  <%= f.submit "Continue", class: "btn btn-primary" %>
<% end %>