config/routes.rb
SteppedCareReboot::Application.routes.draw do
  devise_for :participants
  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  scope constraints: { format: 'html' } do
    get 'navigator/next_content', to: 'navigator#show_next_content', as: 'navigator_next_content'
    get 'navigator/contexts/:context_name', to: 'navigator#show_context', as: 'navigator_context'
    get 'navigator/modules/:module_id(/providers/:provider_id/:content_position)', to: 'navigator#show_location', as: 'navigator_location'
    resource :participant_data, only: [:create, :update]
    resource :flow, only: :show
  end

  resources :slideshows do
    resources :slides do
      collection { post :sort }
    end
  end

  namespace :manage do
    get 'groups/:id/edit_slideshows', to: 'groups#edit_slideshows', as: 'slideshows_group'
    get 'groups/:id/edit_tasks', to: 'groups#edit_tasks', as: 'tasks_group'
    resources :groups, only: [:index]
    resources :tasks, only: [:create, :update, :destroy]
  end

  namespace :coach do
    resources :messages, only: [:index, :new, :create]
    resources :received_messages, only: [:index, :show]
    resources :sent_messages, only: :show
  end

  namespace :participants do
    resources :phq_assessments, only: [:new, :create]
    resources :received_messages, only: :index
    resources :task_status, only: [:update]
  end

  root to: 'navigator#show_context'

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end
end

app/models/message.rb
# A message sent from a Participant or User to a Participant or User.
class Message < ActiveRecord::Base
  belongs_to :sender, polymorphic: true
  belongs_to :recipient, polymorphic: true
  has_many :delivered_messages

  validates :subject, :sender, :recipient, presence: true

  before_create :populate_sent_at
  after_create :create_delivered_messages

  def render_body
    rendered = ""

    unless body.nil?
      markdown = Redcarpet::Markdown.new(
        Redcarpet::Render::HTML,
        space_after_headers: true
      )

      rendered += markdown.render(body)
    end

    rendered.html_safe
  end

  private

  def populate_sent_at
    self.sent_at = Time.new
  end

  def create_delivered_messages
    recipient.received_messages.create(message_id: id)
  end
end

app/controllers/coach/messages_controller.rb
module Coach
  # Manages coach message handling.
  class MessagesController < ApplicationController
    before_action :authenticate_user!
    layout "coach"

    def index
      render(
        locals: {
          received_messages: current_user.received_messages,
          sent_messages: current_user.sent_messages
        }
      )
    end

    def new
      render(
        locals: {
          message: current_user.build_sent_message,
          participants: current_user.participants
        }
      )
    end

    def create
      @message = current_user.build_sent_message(message_params)

      if @message.save
        redirect_to coach_messages_url, notice: "Message saved"
      else
        errors = @message.errors.full_messages.join(", ")
        flash.now[:alert] = "Unable to save message: #{ errors }"
        render :new
      end
    end

    private

    def message_params
      params
        .require(:message)
        .permit(:recipient_id, :recipient_type, :subject, :body)
    end
  end
end

app/controllers/coach/received_messages_controller.rb
module Coach
  # Enables viewing of messages sent to coaches.
  class ReceivedMessagesController < ApplicationController
    before_action :authenticate_user!
    layout "coach"

    def index
      @received_messages = current_user.received_messages
    end

    def show
      message = current_user.received_messages.find(params[:id])
      message.try(:mark_read)
      render(
        template: "messages/show",
        locals: {
          message: message
        }
      )
    end
  end
end

app/controllers/coach/sent_messages_controller.rb
module Coach
  # Enables viewing of messages sent by coaches.
  class SentMessagesController < ApplicationController
    before_action :authenticate_user!
    layout "coach"

    def show
      render(
        template: "messages/show",
        locals: {
          message: current_user.sent_messages.find(params[:id])
        }
      )
    end
  end
end

app/helpers/coach/messages_helper.rb
module Coach
  # Provides helpers for coach message composition.
  module MessagesHelper
    # Returns grouped options for selecting a section of the site.
    def grouped_options_for_site_link_select
      AppSection::SECTIONS.map do |context, title|
        context_options = modules_for_context(context).map do |m|
          [m.title, navigator_location_path(module_id: m.id)]
        end

        [title, context_options]
      end
    end

    private

    def modules_for_context(c)
      BitPlayer::ContentModule
        .joins(:tool)
        .where("bit_player_tools.title = ?", c)
        .where.not("bit_player_content_modules.title = ''")
    end
  end
end

app/views/coach/messages/index.html.erb
<%= render 'messages/inbox_header', received_messages: received_messages %>

<ul class="list-unstyled" id="received-messages">
  <%= render partial: 'coach/received_messages/received_message', collection: received_messages %>
</ul>

<% if sent_messages.count > 0 %>
  <h3>Sent</h3>

  <ul class="list-unstyled">
    <% sent_messages.each do |msg| %>
      <li><strong><%= msg.recipient.email%></strong> : <%= link_to msg.subject, coach_sent_message_path(msg), class: 'text-muted' %> </li>
    <% end %>
  </ul>
<% end %>

<%= link_to 'Compose', new_coach_message_path, class: 'btn btn-default' %>

app/views/coach/messages/new.html.erb
<%= form_for [:coach, message], html: { role: "form" } do |f| %>
  <div class="form-group">
    <label for="message_recipient_id" class="control-label">To</label>
    <%= f.select :recipient_id, participants.collect { |p| [p.email, p.id] } %>
    <%= f.hidden_field :recipient_type, value: 'Participant' %>
  </div>

  <div class="form-group">
    <label for="message_subject" class="control-label">Subject</label>
    <%= f.text_field :subject, required: true, class: "form-control .col-xs-12 .col-sm-6 .col-md-6 .col-lg-4" %>
  </div>

  <div class="form-group">
    <label class="control-label">Add a link</label>
    <%= select_tag nil, grouped_options_for_select(grouped_options_for_site_link_select), id: 'coach-message-link-selection', prompt: 'Please select...' %>
  </div>

  <div class="form-group">
    <label for="message_body" class="control-label">Message</label>
    <%= f.text_area :body, class: "form-control .col-xs-12 .col-sm-6 .col-md-6 .col-lg-4", rows: 5 %>
  </div>

  <button type="submit" class="btn btn-default">Send</button>
<% end %>

app/views/coach/messages/show.html.erb
<h2><%= message.subject %></h2>

<p><%= message.body %></p>