config/routes.rb
SteppedCareReboot::Application.routes.draw do
  devise_for :participants
  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  scope constraints: { format: 'html' } do
    get 'navigator/next_content', to: 'navigator#show_next_content', as: 'navigator_next_content'
    get 'navigator/contexts/:context_name', to: 'navigator#show_context', as: 'navigator_context'
    get 'navigator/modules/:module_id(/providers/:provider_id/:content_position)', to: 'navigator#show_location', as: 'navigator_location'
    resource :participant_data, only: [:create, :update]
    resource :flow, only: :show
  end

  resources :slideshows do
    resources :slides do
      collection { post :sort }
    end
  end

  namespace :manage do
    get 'groups/:id/edit_slideshows', to: 'groups#edit_slideshows', as: 'slideshows_group'
    get 'groups/:id/edit_tasks', to: 'groups#edit_tasks', as: 'tasks_group'
    resources :groups, only: [:index]
    resources :tasks, only: [:create, :update, :destroy]
  end

  namespace :coach do
    resources :messages, only: [:index, :new, :create]
    resources :received_messages, only: [:index, :show]
    resources :sent_messages, only: :show
  end

  namespace :participants do
    resources :phq_assessments, only: [:new, :create]
    resources :received_messages, only: :index
    resources :task_status, only: [:update]
  end

  root to: 'navigator#show_context'

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end
end

app/models/group.rb
# A set of Participants.
class Group < ActiveRecord::Base
  belongs_to :creator, class_name: "User"

  has_many :memberships, dependent: :destroy
  has_many :active_memberships,
           -> { active },
           class_name: "Membership",
           foreign_key: :group_id,
           dependent: :destroy,
           inverse_of: :active_group
  has_many :tasks
  has_many :active_participants, through: :active_memberships

  validates :title, presence: true, length: { maximum: 50 }
  validates :creator, presence: true
end

app/views/groups/edit.html.erb
<%= link_to '<i class="fa fa-chevron-left"></i> Back to Group Index'.html_safe, groups_path, :class => 'btn btn-default'%>
<h1><%= group.title %> Management</h1>

<h3>Assign New Slideshow</h3>
<%= form_for group_slideshow_join, as: :group_slideshow_join, url: group_slideshow_joins_path, html: { role: "form" } do |f| %>
  <%= render "group_slideshow_joins/fields", f: f %>
  <%= f.submit "Assign", class: "btn btn-primary" %>
<% end %>

<h3>Currently assigned slideshows</h3>
<table class="table table-bordered table-striped table-hover">
  <tr>
    <th>Title</th>
    <th>Release Day</th>
    <th></th>
  </tr>
  <% group_slideshow_joins.each do |join|%>
    <tr id="group-slideshow-join-<%= join.id %>">
      <td><%= join.bit_player_slideshow.title %></td>
      <td><%= join.release_day %></td>
      <td>
        <%= link_to "Edit", edit_group_slideshow_join_path(join), :class => "btn btn-default" %>
        <%= link_to "Remove", group_slideshow_join_path(join), method: :delete, :class => "btn btn-danger" %>
      </td>
    </tr>
  <% end %>
</table>

app/views/groups/index.html.erb
<h1>Select the group you wish to manage</h1>
<table class="table table-bordered table-striped table-hover">
  <tr>
    <th>Title</th>
    <th>Creator</th>
    <th> </th>
  </tr>
  <% groups.each do |group| %>
    <tr>
      <td><%= group.title %></td>
      <td><%= group.creator.email %></td>
      <td><%= link_to "Manage", edit_group_path(group), :class => "btn btn-default" %></td>
    </tr>
  <%end%>
</table>