config/routes.rb
SteppedCareReboot::Application.routes.draw do
  devise_for :participants
  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  scope constraints: { format: 'html' } do
    get 'navigator/next_content', to: 'navigator#show_next_content', as: 'navigator_next_content'
    get 'navigator/contexts/:context_name', to: 'navigator#show_context', as: 'navigator_context'
    get 'navigator/modules/:module_id(/providers/:provider_id/:content_position)', to: 'navigator#show_location', as: 'navigator_location'
    resource :participant_data, only: [:create, :update]
    resource :flow, only: :show
  end

  resources :slideshows do
    resources :slides do
      collection { post :sort }
    end
  end

  namespace :manage do
    get 'groups/:id/edit_slideshows', to: 'groups#edit_slideshows', as: 'slideshows_group'
    get 'groups/:id/edit_tasks', to: 'groups#edit_tasks', as: 'tasks_group'
    resources :groups, only: [:index]
    resources :tasks, only: [:create, :update, :destroy]
  end

  namespace :coach do
    resources :messages, only: [:index, :new, :create]
    resources :received_messages, only: [:index, :show]
    resources :sent_messages, only: :show
  end

  namespace :participants do
    resources :phq_assessments, only: [:new, :create]
    resources :received_messages, only: :index
    resources :task_status, only: [:update]
  end

  root to: 'navigator#show_context'

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end
end

app/models/thought.rb
# A thought recorded by a Participant.
class Thought < ActiveRecord::Base
  EFFECTS = ["helpful", "harmful", "neither"]

  belongs_to :participant
  belongs_to :pattern, class_name: "ThoughtPattern", foreign_key: :pattern_id

  validates :participant, :content, :effect, presence: true
  validates :effect, inclusion: { in: EFFECTS }

  scope :helpful, -> { where(effect: "helpful") }

  scope :harmful, -> { where(effect: "harmful") }

  scope :no_pattern, -> { where(pattern_id: nil) }

  scope :unreflected, lambda {
    where("challenging_thought IS NULL OR act_as_if IS NULL")
    .where(effect: "harmful")
  }
end

app/views/thoughts/_form.html.erb
<%= form_for thought, url: create_path, method: "post", html: { role: "form" } do |f| %>
  <div class="form-group">
    <%= f.text_area :content, size: "60x5", placeholder: "example: This is too hard, I'll never figure it out OR Last time I did this, I had a good time", required: true %>
  </div>

  <div class="form-group">
    <label class="radio-inline">
      This thought is:
    </label>
    <% thought.class::EFFECTS.each do |effect| %>
      <label class="radio-inline">
        <%= f.radio_button :effect, effect, required: true %> <%= effect %>
      </label>
    <% end %>
  </div>

  <button type="submit" class="btn btn-default">Continue</button>
<% end %>

app/views/thoughts/edit_bulk.html.erb
<h2>Let's start by figuring out which thought patterns the harmful thoughts you identified might match.</h2>

<% if thoughts.count > 0 %>
  <h3>One thought you had:</h3>

  <% thoughts.each_with_index do |thought, i| %>
    <%=
      form_for(
        thought,
        url: update_path,
        remote: true,
        html: {
          class: "multi-page",
          style: i == 0 ? '' : 'display: none;',
          role: "form"
        }
      ) do |f|
    %>
      <%= f.hidden_field :id %>

      <div class="well"><%= thought.content %></div>

      <div class="form-group">
        <label for="thought_pattern_id">What thought pattern is this an example of?</label>
        <span class="help-block">(don’t worry if it matches more than one!)</span>
        <%= f.select(:pattern_id, options_for_select(ThoughtPattern.all.map { |p| [p.title, p.id, { :"data-description" => p.description }] }), { prompt: "Select one..." }) %>
      </div>

      <p id="thought-pattern-description"></p>

      <button type="submit" class="btn btn-default">Continue</button>
    <% end %>
  <% end %>
<% else %>
  <h3>You haven't listed any negative thoughts--if this inaccurate, please revisit THINK #1</h3>

  <%= link_to "Continue", navigator_next_content_path, class: "btn btn-primary" %>
<% end %>

app/views/thoughts/index.html.erb
<h2><%= title %></h2>

<%= (introduction ||= "").html_safe %>

<ul>
  <% thoughts.each do |thought| %>
    <li><%= thought.content %></li>
  <% end %>
</ul>

<p><%= (postscript ||= "").html_safe %></p>

app/views/thoughts/new.html.erb
<h2>Now, your turn...</h2>

<p>Try to identify a thought you had today.</p>

<%= render 'thoughts/form', thought: thought, create_path: create_path %>

app/views/thoughts/new_bulk.html.erb
<h2>Now list a few more...</h2>

<%
  placeholders = [
    'an example thought: "I don\’t know why I\'m filling this out, but maybe it will help"',
    'another example: "I\'m a terrible friend" or "They\'re all going to laugh at me',
    'yet another example: "They\'re never going to listen to me"'
  ]
%>
<% thoughts.each_with_index do |thought, i| %>
  <%=
    form_for(
      thought,
      url: create_path,
      remote: true,
      html: {
        class: "multi-page",
        style: i == 0 ? '' : 'display: none;',
        role: "form"
      }
    ) do |f|
  %>
    <div class="form-group">
      <%= f.text_area :content, size: "60x5", placeholder: placeholders[i], required: true %>
    </div>

    <div class="form-group">
      <label class="radio-inline">
        This thought is:
      </label>
      <% thought.class::EFFECTS.each do |effect| %>
        <label class="radio-inline">
          <%= f.radio_button :effect, effect, required: true %> <%= effect %>
        </label>
      <% end %>
    </div>

    <button type="submit" class="btn btn-default">Continue</button>
  <% end %>
<% end %>

app/views/thoughts/unhelpful_thoughts_form.html.erb
<% if thoughts.count >= 1 %>
  <% thoughts.each_with_index do |thought, index| %>
    <div class="multi-form" style="<%= index == 0 ? '' : 'display: none;' %>">
      <p>You said that you thought:</p>
      <p><%= thought.content %></p>
      <p>And that this relates to this unhelpful thought pattern:</p>
      <p><%= thought.pattern.title rescue 'Mark! add a title for this pattern!' %></p>
      <div class="next-page btn btn-default">Continue</div>
    </div>
    <%= form_for thought, url: update_path, html: { class: "multi-form", style: "display: none;", id: index}, remote: true do |f| %>
      <p>Thought <%= index + 1 %> of <%= thoughts.count %></p>
      <p><%#= thought.pattern.explanation%>"Mark! Add an explanation for this pattern!"</p>
      <p>Thinking about:</p>
      <p><%= thought.content %></p>
      <p><%#= thought.pattern.question rescue %>"Mark! Add the question for this pattern!"</p>
      <%= f.text_area :challenging_thought, id: "challenge#{index}" %><br>
      <%= f.hidden_field :id %>
      <%= f.submit "Continue", class: "btn btn-default challenging" %>
    <% end %>
    <%= form_for thought, url: update_path, html: { class: "multi-form", style: "display: none;" }, remote: true do |f| %>
      <p>You thought:</p>
      <p><%= thought.content %></p>
      <br>
      <p>A challenging thought was:</p>
      <p id="challenging-thought<%= index %>"></p>
      <p>What could you do to ACT AS IF you believe this?</p>

      <%= f.text_area :act_as_if %><br>
      <%= f.hidden_field :id %>
      <%= f.submit "Continue", class: "btn btn-default" %>
    <% end %>
  <% end %>
<% else %>
  <p>Please return to section 2 of "Thoughts" to input more thoughts for reflection</p>
<% end %>